# Generated by Django 4.0 on 2022-01-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
